### ISSUE TITLE
feat: modal 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by mun-jihye** [TheJulge/Frontend#1]
## Description
모달 공통 컴포넌트 구현

## Todo
- [x] portal 초기 세팅
- [x] 모달 닫기 훅 구현
- [x] 모달 디자인 구현
- [x] 모달 닫기 기능 구현

## ETC
기타 사항
