### ISSUE TITLE
feat: 공통 filter 컴포넌트 구현

### ISSUE THREAD

**Issue by DHyeon98** [TheJulge/Frontend#12]
## Description
어떤 작업에 관한 이슈 인가요?
- 공통 filter 컴포넌트 구현

## Todo
- [x] 캘린더 컴포넌트화
- [x] 위치 클릭시 뱃지로 표시
- [x] 초기화 클릭시 모든 값 초기화
- [x] x 버튼 클릭시 filter 사라짐 

## ETC
기타 사항
