### ISSUE TITLE
feat: notification modal 구현하기

### ISSUE THREAD

**Issue by mun-jihye** [TheJulge/Frontend#18]
## Description
notification modal 구현하기 

## Todo
- [x] notification modal 디자인 구현
- [x] notification modal background (알림 개수, 닫기 버튼) 구현
- [x] 알림창 구현하기
- [x] 승인, 거절 상태 구분하기

## ETC
기타 사항
