### ISSUE TITLE
feat: 가게 등록 페이지 api 연동

### ISSUE THREAD

**Issue by mun-jihye** [TheJulge/Frontend#51]
## Description
가게 등록 페이지 api 연동

## Todo
- [x] 사용자 입력을 서버에 전송 (post 요청)
- [x] 사용자가 등록한 이미지 서버에 전송
- [x] 사용자가 등록한 이미지를 이미지 사이즈에 맞게 보여주기

## ETC
기타 사항
