### ISSUE TITLE
feat: 내프로필/공고 상세 페이지 모달 이벤트 구현

### ISSUE THREAD

**Issue by janyongs** [TheJulge/Frontend#53]
## Description
내프로필/공고 상세 페이지 모달 이벤트 구현

## Todo
- [x] 테이블 상태탭에서 거절/승인 누를시 모달 창 띄우기
- [ ] 테이블 소개탭 에서 테이블 모달 띄우기
- [ ] 수정 버튼 클릭시 모달 처리

## ETC
기타 사항
