### ISSUE TITLE
refactor: 인증 기능 관련 수정 사항 리팩토링

### ISSUE THREAD

**Issue by suMin-97** [TheJulge/Frontend#54]
## Description
인증 기능 관련한 기타 수정 사항 리팩토링
## Todo
- [x] 로그인, 회원가입 페이지 띄어쓰기 수정
- [x] '/noticeList'로 참조한 경로들 '/' 수정
- [x] middleware Redirection 수정
- [x] SignModal 공통 컴포넌트 모달 폴더로 이동
- [x] 로그인 관련 로직 수정
## ETC
인증 관련된 또 다른 수정사항 있으시면 알려주세요!

**Comment by suMin-97** [comment]
완료
