### ISSUE TITLE
error: 데이터 서버에 전송할 때 타입 맞추기

### ISSUE THREAD

**Issue by mun-jihye** [TheJulge/Frontend#72]
## Error Description
- 데이터 포메팅해서 서버에 전송하기

## Todo
- [x] money input에 콤마를 제거하고 숫자형으로 바꾼 값을 서버에 저장
- [x] 날짜 입력하는 인풋의 값을 `양식: 2023-12-23T00:00:00Z`이 형식으로 맞춰서 전송
- [x] timeInput에 콤마를 제거하고 숫자형으로 바꾼 값을 서버에 저장
