### ISSUE TITLE
fix: 사장 공고 상세 수정

### ISSUE THREAD

**Issue by DHyeon98** [TheJulge/Frontend#92]
## Error Description
에러 상황을 설명해주세요
- 사장 공고 상세 링크 수정
- 공고 상세 스타일 변경
- 지도 아이콘 추가

## Todo
- [x] 공고 상세 링크를 prop으로 받아서 type에 맞게 수정
- [ ] 공고 상세의 컴포넌트를 리팩토링
- [ ] 지도 아이콘과 공유 아이콘 퍼블리싱 및 개발
